"""Magnet-controller-backed state-scan plugin."""

from __future__ import annotations

from stoner_measurement.plugins.state._magnet_controller_plugin import (
    MagnetControllerPluginMixin,
)
from stoner_measurement.plugins.state_scan.base import StateScanPlugin


class MagnetControllerScanPlugin(MagnetControllerPluginMixin, StateScanPlugin):
    """Step the magnet field through a list of set-points.

    Use this plugin when you want the sequence to move the magnet controller
    to a series of discrete field values generated by the scan settings. It is
    the usual choice for field-dependent measurements where data are taken at
    specific target fields rather than continuously during a ramp.

    In the configuration tabs, you choose the magnet-controller settings and
    the scan generator that defines the field points. During execution, the
    plugin ramps to each set-point and waits until the controller reports that
    the target has been reached according to the underlying magnet-controller
    state logic.

    Attributes documented on the mixin and base classes control the detailed
    ramp behaviour, tolerances, and engine integration for more technical
    script-oriented use.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self._init_magnet_controller_plugin()

    @property
    def name(self) -> str:
        return "Magnet Controller"

    @property
    def state_name(self) -> str:
        return "Setpoint"

    @property
    def units(self) -> str:
        return "T"

    def to_json(self) -> dict[str, object]:
        data = super().to_json()
        data.update(self._magnet_settings_to_json())
        return data

    def _restore_from_json(self, data: dict[str, object]) -> None:
        super()._restore_from_json(data)
        self._restore_magnet_settings(data)
