"""Magnet-controller-backed state-scan plugin."""

from __future__ import annotations

from stoner_measurement.plugins.state._magnet_controller_plugin import (
    MagnetControllerPluginMixin,
)
from stoner_measurement.plugins.state_scan.base import StateScanPlugin


class MagnetControllerScanPlugin(MagnetControllerPluginMixin, StateScanPlugin):
    """Step the magnet field through a list of set-points.

    Use this plugin when you want the sequence to move the magnet controller
    to a series of discrete field values generated by the scan settings. It is
    the usual choice for field-dependent measurements where data are taken at
    specific target fields rather than continuously during a ramp.

    In the configuration tabs, you choose the magnet-controller settings and
    the scan generator that defines the field points. During execution, the
    plugin ramps to each set-point and waits until the controller reports that
    the target has been reached according to the underlying magnet-controller
    state logic.

    The magnet-specific tab provides the detailed field-control settings
    defined by :class:`~stoner_measurement.plugins.state._magnet_controller_plugin.MagnetControllerPluginMixin`,
    while the scan tab defines the list of target fields. The Help/About tab
    uses this docstring to describe how those controls work together during a
    stepped field scan.

    Attributes:
        wait_for_stable (bool):
            When inherited mixin settings request it, wait for the magnet
            controller to report a stable field rather than merely reaching the
            nominal target.
        tolerance (float):
            Allowed field error when deciding whether the target has been
            reached.

    Keyword Parameters:
        parent (QObject | None):
            Optional Qt parent object.

    Examples:
        >>> from qtpy.QtWidgets import QApplication
        >>> _ = QApplication.instance() or QApplication([])
        >>> plugin = MagnetControllerScanPlugin()
        >>> plugin.name
        'Magnet Controller'
        >>> plugin.units
        'T'
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self._init_magnet_controller_plugin()
        self.use_plugin_ramp_rate = False

    @property
    def name(self) -> str:
        return "Magnet Controller"

    @property
    def state_name(self) -> str:
        return "Setpoint"

    @property
    def units(self) -> str:
        return "T"

    def to_json(self) -> dict[str, object]:
        data = super().to_json()
        data.update(self._magnet_settings_to_json())
        return data

    def _restore_from_json(self, data: dict[str, object]) -> None:
        super()._restore_from_json(data)
        self._restore_magnet_settings(data)
