"""Magnet-controller-backed state-scan plugin."""

from __future__ import annotations

from stoner_measurement.plugins.state._magnet_controller_plugin import (
    MagnetControllerPluginMixin,
)
from stoner_measurement.plugins.state_scan.base import StateScanPlugin


class MagnetControllerScanPlugin(MagnetControllerPluginMixin, StateScanPlugin):
    """Step the magnet field through a list of set-points.

    Use this plugin when you want the sequence to move the magnet controller
    to a series of discrete field values generated by the scan settings. It is
    the usual choice for field-dependent measurements where data are taken at
    specific target fields rather than continuously during a ramp.

    In the configuration tabs, you choose the magnet-controller settings and
    the scan generator that defines the field points. During execution, the
    plugin ramps to each set-point and waits until the controller reports that
    the target has been reached according to the underlying magnet-controller
    state logic.

    **Settings** selects the ramp rate in tesla per minute (a number or
    expression) and reported controller outputs.
    **Scan** defines targets in tesla; **Data** selects collected values and
    column roles. Target and stability status comes from the shared magnet
    engine. A reported quench stops execution.

    Attributes:
        ramp_rate (float | str):
            Ramp rate in tesla per minute or runtime expression.
        use_plugin_ramp_rate (bool):
            Use the plugin rate for applicable moves.
        report_outputs (list[str] | None):
            Selected controller readbacks; None selects all.
        instance_name (str):
            Inherited Python identifier for this instance in the Script tab and
            QtConsole.
        comment (str):
            Inherited optional note displayed beside this step.
        sequence_engine (SequenceEngine | None):
            Inherited owning engine and its live namespace; None while
            detached.
        scan_generator (BaseScanGenerator):
            Inherited generator defining successive sequence points.
        value (float):
            Inherited current sequence control value.
        ix (int):
            Inherited zero-based iteration index.
        meas_flag (bool):
            Inherited flag indicating a measurement point.
        collect_data (bool):
            Inherited switch enabling collection of selected sequence outputs.
        data (TraceData):
            Inherited accumulated table; inspect data.df after collection.

    Keyword Parameters:
        parent (QObject | None):
            Optional Qt parent object.

    Examples:
        With a sequence instance named ``magnet_controller_scan``, use
        the QtConsole to inspect or edit it before running. Substitute your
        instance name if different; result data reflects completed steps::

            magnet_controller_scan.ramp_rate = 0.1
            magnet_controller_scan.collect_data = True
            magnet_controller_scan.data.df.head()
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self._init_magnet_controller_plugin()
        self.use_plugin_ramp_rate = False

    @property
    def name(self) -> str:
        return "Magnet Controller"

    @property
    def state_name(self) -> str:
        return "Setpoint"

    @property
    def units(self) -> str:
        return "T"

    def to_json(self) -> dict[str, object]:
        data = super().to_json()
        data.update(self._magnet_settings_to_json())
        return data

    def _restore_from_json(self, data: dict[str, object]) -> None:
        super()._restore_from_json(data)
        self._restore_magnet_settings(data)
