"""Temperature-controller-backed state-scan plugin."""

from __future__ import annotations

from stoner_measurement.plugins.state._temperature_controller_plugin import (
    TemperatureControllerPluginMixin,
)
from stoner_measurement.plugins.state_scan.base import StateScanPlugin


class TemperatureControllerScanPlugin(TemperatureControllerPluginMixin, StateScanPlugin):
    """Step temperature through a list of set-points.

    Use this plugin when you want the sequence to move the temperature
    controller to a series of discrete target temperatures generated by the
    scan settings. It is the usual choice for temperature-dependent
    measurements where data are taken after stabilising at each set-point.

    In the configuration tabs, you choose the temperature-controller settings
    and the scan generator that defines the temperature points. During
    execution, the plugin ramps to each set-point and waits until the engine
    reports that the selected control loop is stable.

    **Settings** selects **Control loop**, **Stability timeout** in minutes
    (a number or per-point expression), and **Reported sensors** (blank means
    all known sensors). **Scan** defines temperatures in kelvin and **Data**
    selects collected outputs and column roles. On stability timeout the scan
    continues with its timed-out flag set; it does not assert stability.

    Attributes:
        settle_timeout_minutes (float | str):
            Maximum time to wait for the selected loop to become stable at
            each set-point, as a number or runtime expression in minutes.
            Expressions are reevaluated at each point and may refer to the
            current target through :attr:`value`. Defaults to ``20.0``.
        timed_out (bool):
            Whether the most recent set-point wait reached its stability
            timeout.
        control_loop (int):
            One-based control loop; defaults to 1.
        sensor_channels (list[str] | None):
            Reported sensors; None selects all known sensors.
        instance_name (str):
            Inherited Python identifier for this instance in the Script tab and
            QtConsole.
        comment (str):
            Inherited optional note displayed beside this step.
        sequence_engine (SequenceEngine | None):
            Inherited owning engine and its live namespace; None while
            detached.
        scan_generator (BaseScanGenerator):
            Inherited generator defining successive sequence points.
        value (float):
            Inherited current sequence control value.
        ix (int):
            Inherited zero-based iteration index.
        meas_flag (bool):
            Inherited flag indicating a measurement point.
        collect_data (bool):
            Inherited switch enabling collection of selected sequence outputs.
        data (TraceData):
            Inherited accumulated table; inspect data.df after collection.

    Keyword Parameters:
        parent (QObject | None):
            Optional Qt parent object.

    Examples:
        With a sequence instance named ``temperature_controller_scan``, use
        the QtConsole to inspect or edit it before running. Substitute your
        instance name if different; result data reflects completed steps::

            temperature_controller_scan.control_loop = 2
            temperature_controller_scan.settle_timeout_minutes = 30.0
            temperature_controller_scan.timed_out
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self._init_temperature_controller_plugin()
        self.settle_timeout_minutes: float | str = 20.0

    @property
    def name(self) -> str:
        return "Temperature Controller"

    @property
    def state_name(self) -> str:
        return "Setpoint"

    @property
    def units(self) -> str:
        return "K"

    @property
    def settle_timeout(self) -> float:
        """Return the configured stability timeout in seconds."""
        return 60.0 * max(0.1, self.eval_float(self.settle_timeout_minutes))

    def to_json(self) -> dict[str, object]:
        data = super().to_json()
        data.update(self._temperature_settings_to_json())
        data["settle_timeout_minutes"] = self.settle_timeout_minutes
        return data

    def _restore_from_json(self, data: dict[str, object]) -> None:
        super()._restore_from_json(data)
        self._restore_temperature_settings(data)
        if "settle_timeout_minutes" in data:
            value = data["settle_timeout_minutes"]
            if isinstance(value, (int, float, str)):
                self.settle_timeout_minutes = value
