"""Temperature-controller-backed state-scan plugin."""

from __future__ import annotations

from stoner_measurement.plugins.state._temperature_controller_plugin import (
    TemperatureControllerPluginMixin,
)
from stoner_measurement.plugins.state_scan.base import StateScanPlugin


class TemperatureControllerScanPlugin(TemperatureControllerPluginMixin, StateScanPlugin):
    """Step temperature through a list of set-points.

    Use this plugin when you want the sequence to move the temperature
    controller to a series of discrete target temperatures generated by the
    scan settings. It is the usual choice for temperature-dependent
    measurements where data are taken after stabilising at each set-point.

    In the configuration tabs, you choose the temperature-controller settings
    and the scan generator that defines the temperature points. During
    execution, the plugin ramps to each set-point and waits until the engine
    reports that the selected control loop is stable.

    The temperature-specific tab provides the detailed control-loop and
    stability settings defined by
    :class:`~stoner_measurement.plugins.state._temperature_controller_plugin.TemperatureControllerPluginMixin`,
    while the scan tab defines the list of target temperatures. The Help/About
    tab uses this docstring to describe how those controls work together
    during a stepped temperature scan.

    Attributes:
        loop (int):
            Control loop used by the underlying mixin to apply set-points.
        settle_timeout_minutes (float | str):
            Maximum time to wait for the selected loop to become stable at
            each set-point, as a number or runtime expression in minutes.
            Expressions are reevaluated at each point and may refer to the
            current target through :attr:`value`. Defaults to ``20.0``.
        timed_out (bool):
            Whether the most recent set-point wait reached its stability
            timeout.
    Keyword Parameters:
        parent (QObject | None):
            Optional Qt parent object.

    Examples:
        >>> from qtpy.QtWidgets import QApplication
        >>> _ = QApplication.instance() or QApplication([])
        >>> plugin = TemperatureControllerScanPlugin()
        >>> plugin.name
        'Temperature Controller'
        >>> plugin.units
        'K'
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self._init_temperature_controller_plugin()
        self.settle_timeout_minutes: float | str = 20.0

    @property
    def name(self) -> str:
        return "Temperature Controller"

    @property
    def state_name(self) -> str:
        return "Setpoint"

    @property
    def units(self) -> str:
        return "K"

    @property
    def settle_timeout(self) -> float:
        """Return the configured stability timeout in seconds."""
        return 60.0 * max(0.1, self.eval_float(self.settle_timeout_minutes))

    def to_json(self) -> dict[str, object]:
        data = super().to_json()
        data.update(self._temperature_settings_to_json())
        data["settle_timeout_minutes"] = self.settle_timeout_minutes
        return data

    def _restore_from_json(self, data: dict[str, object]) -> None:
        super()._restore_from_json(data)
        self._restore_temperature_settings(data)
        if "settle_timeout_minutes" in data:
            value = data["settle_timeout_minutes"]
            if isinstance(value, (int, float, str)):
                self.settle_timeout_minutes = value
