"""Temperature-controller-backed state-scan plugin."""

from __future__ import annotations

from stoner_measurement.plugins.state._temperature_controller_plugin import (
    TemperatureControllerPluginMixin,
)
from stoner_measurement.plugins.state_scan.base import StateScanPlugin


class TemperatureControllerScanPlugin(TemperatureControllerPluginMixin, StateScanPlugin):
    """Step temperature through a list of set-points.

    Use this plugin when you want the sequence to move the temperature
    controller to a series of discrete target temperatures generated by the
    scan settings. It is the usual choice for temperature-dependent
    measurements where data are taken after stabilising at each set-point.

    In the configuration tabs, you choose the temperature-controller settings
    and the scan generator that defines the temperature points. During
    execution, the plugin ramps to each set-point and waits until the
    controller reports that the target has been reached according to the
    underlying temperature-controller state logic.

    Attributes documented on the mixin and base classes control the detailed
    loop selection, stability handling, ramp behaviour, and engine integration
    for more technical script-oriented use.
    """

    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self._init_temperature_controller_plugin()

    @property
    def name(self) -> str:
        return "Temperature Controller"

    @property
    def state_name(self) -> str:
        return "Setpoint"

    @property
    def units(self) -> str:
        return "K"

    def to_json(self) -> dict[str, object]:
        data = super().to_json()
        data.update(self._temperature_settings_to_json())
        return data

    def _restore_from_json(self, data: dict[str, object]) -> None:
        super()._restore_from_json(data)
        self._restore_temperature_settings(data)
